### ISSUE TITLE
Question about optimizer in code

### ISSUE THREAD

**Issue by adam4096** [REIYANG/FedBCD#1]
Hi Ruiyuan,
I have a question:
In your paper, you used BCD for local updates. But in your code, I found that you used

_optimizer = optim.SGD(net.parameters(), lr=learning_rate, momentum=0.9, weight_decay=0.0001)_

from FedBCD/experiment I/MNIST-FedBCD-sync.ipynb In [13].

Why is different

**Comment by REIYANG** [comment]
Hi, thanks for your attention to this work!

Yes, we consider BCD to tackle the whole problem. And for each of the local updates (say, the updates on edge devices), we adopt SGD to update the local models (or personalized models in the paper), c.f. Eq(4) in the paper. To this end, we directly use the SGD optimizer to handle this task.

**Comment by adam4096** [comment]
> Hi, thanks for your attention to this work!
> 
> Yes, we consider BCD to tackle the whole problem. And for each of the local updates (say, the updates on edge devices), we adopt SGD to update the local models (or personalized models in the paper), c.f. Eq(4) in the paper. To this end, we directly use the SGD optimizer to handle this task.
